on:
  pull_request:
    type: [opened, reopened, synchronize]

jobs:
  build:
    runs-on: ubuntu-22.04
    # Because the testing job is different, we need to out the Netlify URL so we can access it in another job
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idoutputs
    outputs:
      deploy_url: ${{steps.build_site.outputs.NETLIFY_URL}}
    steps:
      - name: Checkout Repo Code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Node Modules
        run: npm install

      - name: Deploy to Netlify
        id: build_site
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: ./_actions/netlify_deploy.sh

      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'The build works! You can view the deploy preview at ${{steps.build_site.outputs.NETLIFY_URL}}'
            })

  # Creating a new job for the tests to run in
   test:
    needs: build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo Code
        uses: actions/checkout@v3

      - name: Install Packages
        run: npm run ci
      
      # - name: Percy Test
      #   env:
      #     PERCY_TOKEN: ${{secrets.PERCY_TOKEN}}
      #   run: npx @percy/cli snapshot tests/vr/snapshots.yml --base-url ${{needs.build.outputs.deploy_url}}

      - name: Run Playwright Tests
        run: npm run test:ui:ci
        env:
          SITE_URL: ${{needs.build.outputs.deploy_url}}
        
      - name: Upload Playwright Report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: tests/ui/results/reports/
          retention-days: 30